name: Building recovery

on:
#  release:
#    types: [published]
  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
  MANIFEST_BRANCH: twrp-12.1
  DEVICE: veux
  DT_LINK: https://github.com/anant-goel/orangefox_device_xiaomi_veux
  DT_PATH: device/xiaomi/veux
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            git config --global user.name "ElytrA8"
            git config --global user.email "manofuranium@gmail.com"         
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            git clone https://github.com/akhilnarang/scripts --depth=1
            cd scripts
            sudo bash setup/android_build_env.sh
            cd .. 
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST -b $MANIFEST_BRANCH --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -j4
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh &&lunch twrp_$DEVICE-userdebug &&export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET
             
       - uses: actions/upload-artifact@v2
         with:
          name: recoveryzip
          path: work/out/target/product/*/*.zip

       - uses: actions/upload-artifact@v2
         with:
          name: recoveryimage
          path: work/out/target/product/*/*.img
